scalar Text

type BatchRequest {
  id: String!
  total_borrowed: Int!
  total_repaid: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type BatchResponse {
  id: String!
  lusd_amount: Int!
  eth_amount: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}
